---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:oauth_token: 240692635-SMssU4QdbAKdtgeZG71pip5Q2B5IouUlas456Zrf
:oauth_secret: ZFePp1yWKZmuonZTyoNLzW6eNl3sWywPym7vU0n5E0UL0
